# Generated by Django 4.0.3 on 2022-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('t_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=400, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi  ',
                'verbose_name_plural': 'Foydalanuvchilar  ',
            },
        ),
    ]
